"""
Collatz Conjecture Analyzer

Analyzes sequences generated by the Collatz conjecture for different starting numbers.
The Collatz conjecture states that for any positive integer n:
- If n is even, divide by 2: n → n/2
- If n is odd, multiply by 3 and add 1: n → 3n + 1
- Repeat until you reach 1

The conjecture claims that all sequences eventually reach 1, but this has not been proven.
"""

def collatz_sequence(n):
    """
    Generate the Collatz sequence starting from n.
    
    Args:
        n: Starting positive integer
    
    Returns:
        List of integers in the sequence until it reaches 1
    """
    sequence = [n]
    
    while n != 1:
        if n % 2 == 0:
            n = n // 2
        else:
            n = 3 * n + 1
        sequence.append(n)
    
    return sequence


def analyze_collatz(start, end):
    """
    Analyze Collatz sequences for all numbers in a range.
    
    Args:
        start: Starting number of the range
        end: Ending number of the range (inclusive)
    
    Returns:
        Dictionary with statistics about the sequences
    """
    results = {
        'sequences': {},
        'max_length': 0,
        'max_length_number': 0,
        'max_value': 0,
        'max_value_number': 0,
        'total_sequences': 0
    }
    
    for num in range(start, end + 1):
        sequence = collatz_sequence(num)
        length = len(sequence)
        max_val = max(sequence)
        
        results['sequences'][num] = {
            'sequence': sequence,
            'length': length,
            'max_value': max_val
        }
        
        if length > results['max_length']:
            results['max_length'] = length
            results['max_length_number'] = num
        
        if max_val > results['max_value']:
            results['max_value'] = max_val
            results['max_value_number'] = num
        
        results['total_sequences'] += 1
    
    return results


def print_sequence_analysis(num, sequence):
    """Print detailed analysis of a single sequence."""
    print(f"\n{'=' * 60}")
    print(f"Collatz Sequence for n = {num}")
    print(f"{'=' * 60}")
    print(f"Sequence length: {len(sequence)} steps")
    print(f"Maximum value reached: {max(sequence)}")
    print(f"\nSequence: {' → '.join(map(str, sequence))}")
    print(f"\nSequence ends at: {sequence[-1]}")


def print_statistics(results):
    """Print statistics about multiple sequences."""
    print(f"\n{'=' * 60}")
    print("Collatz Conjecture Analysis Statistics")
    print(f"{'=' * 60}")
    print(f"Total sequences analyzed: {results['total_sequences']}")
    print(f"\nLongest sequence:")
    print(f"  Starting number: {results['max_length_number']}")
    print(f"  Length: {results['max_length']} steps")
    
    longest_seq = results['sequences'][results['max_length_number']]['sequence']
    print(f"  Sequence: {longest_seq[:10]}... (showing first 10)")
    
    print(f"\nHighest value reached:")
    print(f"  Starting number: {results['max_value_number']}")
    print(f"  Maximum value: {results['max_value']}")
    
    max_seq = results['sequences'][results['max_value_number']]['sequence']
    print(f"  Sequence: {max_seq[:10]}... (showing first 10)")


def find_patterns(results):
    """Find interesting patterns in the sequences."""
    print(f"\n{'=' * 60}")
    print("Pattern Analysis")
    print(f"{'=' * 60}")
    
    # Find numbers that take the same number of steps
    length_groups = {}
    for num, data in results['sequences'].items():
        length = data['length']
        if length not in length_groups:
            length_groups[length] = []
        length_groups[length].append(num)
    
    # Show groups with multiple numbers having the same length
    common_lengths = {k: v for k, v in length_groups.items() if len(v) > 1}
    if common_lengths:
        print("\nNumbers with the same sequence length:")
        for length in sorted(common_lengths.keys())[:5]:  # Show first 5
            print(f"  Length {length}: {common_lengths[length][:10]}...")


def main():
    print("=" * 60)
    print("Collatz Conjecture Analyzer")
    print("=" * 60)
    
    # Analyze a single interesting number
    print("\nAnalyzing individual sequences:")
    interesting_numbers = [27, 97, 871, 6171]
    
    for num in interesting_numbers:
        sequence = collatz_sequence(num)
        print_sequence_analysis(num, sequence)
    
    # Analyze a range of numbers
    print("\n" + "=" * 60)
    print("Analyzing range of numbers...")
    start = 1
    end = 100
    
    print(f"\nAnalyzing Collatz sequences for numbers {start} to {end}...")
    results = analyze_collatz(start, end)
    
    print_statistics(results)
    find_patterns(results)
    
    print("\n" + "=" * 60)
    print("Note: The Collatz conjecture states that all sequences")
    print("eventually reach 1, but this has not been mathematically proven.")
    print("=" * 60)


if __name__ == "__main__":
    main()

